### ISSUE TITLE
Our extended abstract in CVPR 2017 DeepVision Workshop

### ISSUE THREAD

**Issue by xavigiro** [sootlasten/disentangled-representation-papers#1]
Thanks for this nice list of papers. We presented an extended abstract last year in CVPR that you might want to consider. Source code is available in TensorFlow.

Lin, Xunyu, Victor Campos, Xavier Giro-i-Nieto, Jordi Torres, and Cristian Canton Ferrer. [“Disentangling Motion, Foreground and Background Features in Videos.”](https://imatge-upc.github.io/unsupervised-2017-cvprw/) CVPR Workshop: Brave new ideas for motion representations in videos II (2017).

We are currently working on a full paper which should be available by the end of 2018.

**Comment by sootlasten** [comment]
Thank you for the interesting work. I added it to my list as well, hopefully will find the time to read it soon. The good thing about this field of research is that it's small enough that one can indeed manage to read most of the published papers.
