### ISSUE TITLE
 Unsupervised Learning of Disentangled and Interpretable Representations from Sequential Data

### ISSUE THREAD

**Issue by pfriesch** [sootlasten/disentangled-representation-papers#2]
This paper might be interesting to add to the list:
[Unsupervised Learning of Disentangled and Interpretable Representations from Sequential Data](https://arxiv.org/abs/1709.07902)
[Code](https://github.com/wnhsu/ScalableFHVAE)

**Comment by sootlasten** [comment]
Absolutely, added to the list. The amount of question marks in the list, marking the papers I haven't read, is quickly becoming overwhelming.
